# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.9-alpine
stages:
  - prepare
#  - test
  - build
  - package

#test:lint:
#  stage: test
#  script: npm run lint

prepare:
  stage: prepare
  cache:
    paths:
      - node_modules/
  script:
   - npm i

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - scripts/
      - bootstrap.js
  script:
    - npm run build
    - npm run build_bootstrap
  artifacts:
    paths:
      - scripts/

package:
  stage: package
  cache:
    paths:
      - node_modules/
      - scripts/
  script:
    - apk update
    - apk add xz
    - tar -cf - scripts/ | xz -9 -c - > scripts.tar.xz
    - tar -cf - node_modules/ | xz -9 -c - > node_modules.tar.xz
  artifacts:
    paths:
      - scripts.tar.xz
      - node_modules.tar.xz
      - bootstrap.js
